[package]
name = "criterion-test"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "sort_benchmarks"
harness = false
